spring.application.name=codeb-ims-backend

spring.datasource.url=jdbc:mysql://localhost:3307/codeb_ims
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080